# run with `cargo make <task>`

[tasks.fmt-unstable]
command = "cargo"
args = [
    "fmt",
    "--",
    "--check",
    "--config",
    "use_field_init_shorthand=true,unstable_features=true,format_code_in_doc_comments=true,format_generated_files=false,format_strings=true,group_imports=StdExternalCrate,imports_granularity=Crate,normalize_comments=true,reorder_impl_items=true,wrap_comments=true",
]
